version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    volumes:
      - ./frontend/puplic:/usr/share/nginx/html

