apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: express-server
  template:
    metadata:
      labels:
        app: express-server
    spec:
      containers:
      - name: express-server
        image: ilonagoergens/express-server:latest
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: express-server-service
spec:
  selector:
    app: express-server
  ports: 
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: NodePort

